services:
  server:
    build: server
    command: [ "-c", "configs/docker.dev.json" ]
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./server/configs:/app/configs
    depends_on:
      db:
        condition: service_healthy
      broker:
        condition: service_started
  
  publisher:
    build: publisher
    command: [ "-c", "configs/docker.dev.json" ]
    restart: unless-stopped
    volumes:
      - ./publisher/configs:/app/configs
    depends_on:
      - server

  db:
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "$$POSTGRES_USER", "-d", "$$POSTGRES_DB" ]
      interval: 30s
      timeout: 10s
      retries: 5

  broker:
    image: nats-streaming:0.25.6-linux
    restart: unless-stopped
    command: ["-cid", "app-cluster"]
    ports:
      - 4222:4222
